### ISSUE TITLE
Export lenses

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#1]
We should export at least `use` and `.=`, because we have banished `put` and `get`; but in practice, all of lens is useful occasionally. However, lens is a huge dependency, so instead I propose to use microlens and reexport `Lens.Micro.Platform` in `Microlens` module (but not from `Universum` – we want to avoid clashes if in some project we decide to use lens).

**Comment by gromakovsky** [comment]
I don't like the idea of having `lens` as a dependency of `universum`, because it is very heavy. I don't object to exporting something from `microlens` and `microlens-mtl` though. But I would like to postpone it and only if we decide that it is necessary. After all, we didn't completely banish `put` and `get`, you can always import them manually.

**Comment by ChShersh** [comment]
I also don't like idea of bringing `lens` into `Universum`. Though they might be useful but they are really very heavy. And we actually don't use them in each module.
Regarding `microlens`: I expect some conflicts with `lens` library. As far as I know none of each two `*lens` libraries compatible between each other. But I may be wrong. @neongreen you're lens expert here :)

**Comment by neongreen** [comment]
Okay, just to clarify: by “but in practice, all of lens is useful occasionally” I didn't mean that we should export the whole of `lens`-the-package, just that (all) lens libraries provide more useful things than `use` and `.=`.

@ChShersh There will be conflicts, which is exactly why lenses would be exported from `Microlens` (or `Lens`? I don't know what name would be better, probably `Lens`) instead of `Universum`, so that it'd be possible to switch `Lens` to `Control.Lens` at any point. Actual lenses defined with either library are compatible with each other.

**Comment by ChShersh** [comment]
Okay, if you say they are compatible that I don't have any objections against exports from some small library.
