### ISSUE TITLE
Generalise concat and concatMap

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#10]
Currently we have:

```haskell
concat :: Foldable t => t [a] -> [a]
concatMap :: Foldable t => (a -> [b]) -> t a -> [b]
```

I'd like them to be generalised to:

```haskell
concat :: (Foldable t, Monoid a) => t a -> a
concatMap :: (Foldable t, Monoid b) => (a -> b) -> t a -> b
```

**Comment by ChShersh** [comment]
Generalized version of `concan` is basically `mconcat` of even `fold`. And `concatMap` is `foldMap`. I'd better suggest to export those functions from `Data.Foldable` because `concatMap` is not proper name for it does in generalized version. But dunno.

**Comment by neongreen** [comment]
`mconcat` isn't generalised for `Foldable`.

On the other hand, yeah, `fold` and `foldMap` are exactly what I want. I don't know how I missed them.

**Comment by gromakovsky** [comment]
As far as I understand, `fold` and `foldMap` are already exported. Can we close this issue?

**Comment by neongreen** [comment]
Yep.
