### ISSUE TITLE
Add bug=impureThrow

### ISSUE THREAD

**Issue by int-index** [serokell/universum#100]
Define `bug` roughly as follows:

```
import Control.Exception.Safe (impureThrow)

data Bug = Bug SomeException CallStack

instance Exception Bug

bug :: (HasCallStack, Exception e) => e -> a
bug e = impureThrow $ Bug (toException e) ?callStack
```

**Comment by ChShersh** [comment]
@int-index Could you please explain why we need to store `HasCallStack` explicitly in `Bug` constructor?

**Comment by int-index** [comment]
Because we want to use it in `displayException` for `Bug`.

**Comment by int-index** [comment]
That is how it is done for `ErrorCall`.
