### ISSUE TITLE
fromIntegral

### ISSUE THREAD

**Issue by h4ck3rm1k3** [serokell/universum#110]
Where is fromIntegral defined if not in prelude? 
http://hackage.haskell.org/package/base-4.10.1.0/docs/Prelude.html#v:fromIntegral

**Comment by ChShersh** [comment]
If you navigate to `fromIntegral` sources you can see that this function is defined in `GHC.Real` module:

* https://www.stackage.org/haddock/lts-10.2/base-4.10.1.0/src/GHC-Real.html#fromIntegral

`universum` reexports almost everything from this module:

* https://github.com/serokell/universum/blob/156eab5e756117c53fa708e111b13c1a67f8a8d7/src/Universum/Base.hs#L83

Does this clarify things for you?

**Comment by h4ck3rm1k3** [comment]
Thank you!
