### ISSUE TITLE
Add `chooose`

### ISSUE THREAD

**Issue by Martoon-00** [serokell/universum#111]
I lack of `choose :: Alternative f => [f a] -> f a` function, it seems to be only exported by various parser packages.
(AFAIR @gromakovsky once also searched for this function).

Also `choose1 :: Alternative f => [a -> f b] -> a -> f b` seem helpful for writing parsers for JSON instances.

**Comment by int-index** [comment]
man, it's `asum`

**Comment by ChShersh** [comment]
@Martoon-00 `choose` is `asum` and work for every `Foldable`, not only list.

`choose1` migth be useful! But it can be defined simply as

```haskell
choose1 choices a = asum $ map ($ a) choices
```

I don't think this function is that common to put it into custom prelude... Can you give more examples and usages other than just writing parsers?

**Comment by int-index** [comment]
By the way, `choose1` is a bad name, normally I expect `1` in the name to be either a function for non-empty containers or for types of kind `* -> *`.

**Comment by Martoon-00** [comment]
Yeah right, perhaps it's not worth that then
