### ISSUE TITLE
Faster merge sort

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#112]
It's claimed that this implementation of merge sort based on mutable arrays is faster than standard `sort` from `base` package:

* https://github.com/YakutovDmitriy/Functional-Programming/blob/master/hw4/src/Sorts.hs

I guess this can be investigated.

**Comment by johnchandlerburnham** [comment]
Is there a good Haskell library with a collection of different sorting algorithms? Something with a good timsort or blocksort implementation maybe?

I can't find anything that looks well-used: https://hackage.haskell.org/packages/search?terms=sort

**Comment by ChShersh** [comment]
@johnchandlerburnham No, there's no such library, AFAIK. Sorting algorithms are not really researched well in pure immutable Haskell setting...

**Comment by rpglover64** [comment]
There's this: https://hackage.haskell.org/package/vector-algorithms

**Comment by ChShersh** [comment]
@rpglover64 Nice! Thanks for suggestion. I don't think this should be included in custom prelude. And I also don't think that we should introduce any other functions for this. Reexporting standard sorting algorithms is already fine! But still good to know about `vector-algorithms` library.
