### ISSUE TITLE
Annotate functions with 'LiquidHaskell'

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#113]
LiquidHaskell is a great tool! Before trying it on big projects, we should enhance our infrastructure libraries. Custom prelude `universum` is a great target for being annotated with LiquidHaskell. Also, once `base` is annotated, we can reuse specs from `base` in our functions!

So the plan is:

- [x] Read some LiquidHaskell tutorials
- [x] Try to launch `liquidhaskell` following [instructions for `cardano-sl`](https://gist.github.com/denisshevchenko/00bfdb4e06de1637d1743375ec90e9e6)
- [x] Come up with the list of some properties for `universum` (this list should at least contain `Min` property)
- [x] Impelement those property
- [x] Think about how to prove functions totality and which functions can be proven

**Comment by gromakovsky** [comment]
> Also, once base is annotated

Do we know it will happen relatively soon? Just curious and lazy to google :)

**Comment by ChShersh** [comment]
@gromakovsky These annotations are already written during last year Haskell Summer of Code

* https://summer.haskell.org/news/2017-09-15-final-results.html

The work can be found here:

* https://github.com/sdleffler/ghc/tree/ghc-8.0

I contacted mentor of this HSOC project. Maybe she can share plans regarding merging this work into `base` package eventually.

**Comment by ChShersh** [comment]
@nikivazou Answered me the following:

> Hi Dmitry, 
> I am indeed the best person to reach as I was co mentoring this project. Sadly, it didn't go very well and until the end, there was nothing ready to merge... 
> If you have time to play with it, feel free to merge it:)

So, probably, seems like there's not a single person at the moment who is actively working on LiquidHaskell annotations for `base` package and we probably shouldn't count on that :disappointed:

**Comment by ChShersh** [comment]
This is partially done in PR #156. More properties can be suggested and added under different issues.
