### ISSUE TITLE
Export more from safe-exceptions

### ISSUE THREAD

**Issue by int-index** [serokell/universum#114]
I studied the Cardano SL codebase and discovered that we explicitly import the following definitions from `safe-exceptions`:

* `Exception`
* `MonadCatch`
* `MonadMask`
* `MonadThrow`
* `SomeException`
* `bracket`
* `bracketOnError`
* `catch`
* `catchAny`
* `displayException`
* `finally`
* `handle`
* `handleAny`
* `handleAsync`
* `mask_`
* `onException`
* `throwM`
* `throwString`
* `try`
* `tryAny`
* `handle`

I propose that we re-export them from Universum, except for `throwString` and `handleAsync`.

**Comment by ChShersh** [comment]
I don't mind reexporting those functions. But I also want to prohibit `handle` because it's a very popular name for variable.
