### ISSUE TITLE
Change 'identity' to 'id' back

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#129]
This is more user friendly.

**Comment by gromakovsky** [comment]
Sometimes I even see `import Data.Function (id)`.

**Comment by volhovm** [comment]
I'd leave both of them to preserve backward compatibility. The original point was "id is a good name for some variable", but as far as i see, it's a super rare usecase.

**Comment by johnchandlerburnham** [comment]
`id :: a -> a` is basically an idiom. If used as a variable, it's sort-of like an implicit overloading that might confuse people. There are other options for variable naming like `idN` or `idT` that are almost as good

**Comment by ChShersh** [comment]
Let's export `id` but keep `identity` as well for compatibility.
