### ISSUE TITLE
Merge 'ToList' and 'Container' into single type class 'Container'

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#130]
I don't see point in having both `ToList` and `Container`. Maybe @neongreen can clarify. But I think second type class is redundant.

**Comment by neongreen** [comment]
The reason I made two classes was that I wanted e.g. `Maybe` to have `toList` but not other `Container` stuff:

```
DISALLOW_CONTAINER_8((a, b),"tuples")
DISALLOW_CONTAINER_8(Maybe a,"Maybe")
DISALLOW_CONTAINER_8(Identity a,"Identity")
DISALLOW_CONTAINER_8(Either a b,"Either")
```

This said, now I don't see why I did that :/ Okay, let's merge them and have just `Container`.
