### ISSUE TITLE
Shorten 'evaluatingStateT' and family

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#131]
`evaluatingStateT` is longer than `flip runStateT`. Many people complained about that. So I think we can shorten this. I propose to have `evaling/execing`. Compare:

```haskell
evaluatingStateT
flip runStateT
evalingStateT
```

Though, maybe it's really minor and just a micro-optimization 🤷‍♀️

**Comment by volhovm** [comment]
`run/exec/evalSomethingT` is not that common to change the lib interface imho.

**Comment by volhovm** [comment]
Against it.

**Comment by ChShersh** [comment]
Okay, looks like not much people care. So I'm closing this.
