### ISSUE TITLE
Change type of foldl' back and implement 'foldL' instead 

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#136]
`foldl' (/) 1 [2,3]` doesn't do what it should according to type.

And changing type of `foldl'` introduces silent breakage.

Naming is another question. As well as an implementation of this function.

**Comment by ChShersh** [comment]
Several unresolved questions:

1. Naming? `foldL` or `foldLeft` or `flipfoldl'` or something else?
2. Should it be polymorphic over container type class?
3. Should we implement it manually or as `foldl' . flip`?

**Comment by volhovm** [comment]
I don't really care about `foldlL` or whatever you'd like to call it, but since this issue is linked with "revert that change", I must write something. So I do. Please revert. :)

**Comment by Pastafarianist** [comment]
Perhaps `foldlF`/`foldlF'` and similarly for `foldr` would do.

**Comment by ChShersh** [comment]
@Pastafarianist What this `F` stands for?

**Comment by volhovm** [comment]
"flipped", but this is counterntuitive. `F` in the end of the word usually means "Functor". `flipFoldl(')` is better.

**Comment by int-index** [comment]
I agree with @volhovm , the F in the end immediately makes me think of functors. But I'd prefer `flipfoldl` to `flipFoldl` for aesthetic reasons.

**Comment by ChShersh** [comment]
Okay, I can introduce new function:

```haskell
flipfoldl :: (Container t, Element t ~ a) => (a -> b -> b) -> b -> t -> b
```

with strict semantic and implement it manually for every data type.

**Comment by int-index** [comment]
> with strict semantic and implement it manually for every data type.

I'd expect `flipfoldl' f = foldl' (flip f)` with whatever type signature is inferred.
