### ISSUE TITLE
Nice, convenient and idiomatic way to handle Maybe's

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#15]
I propose to add next operators in `Universum` to work with `Maybe` in even more nice way:

``` haskell
(?:) = flip fromMaybe  -- elvis operator

m !!: s = m ?: error s  -- unsafe elvis operator

(?.) = (>>=)  -- specialisation for Maybe
```

So it should be possible to write code like this one:

`tail args?.head?.readMaybe ?: 0`

**Comment by ChShersh** [comment]
Also consider this (I'll just put it here):

https://twitter.com/Iceland_jack/status/883314861924593664

**Comment by vrom911** [comment]
@ChShersh , I like `(?:)` option :100: 
But I'm not sure that introducing the pattern for `Maybe` constructors would be great thing to do.. :thinking:

**Comment by ChShersh** [comment]
I don't think we need to have `?.` operator. `>>=` is more common and known to people. Though, `?:` looks idiomatic. We don't want to have partial functions in `universum` so I don't think we need to have `:!!`.
