### ISSUE TITLE
Investigate issues with 'universum' in stackage nightly snapshot

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#159]
Somehow `universum-1.1.0` is not in latest Stackage Nightly:

* https://www.stackage.org/nightly-2018-04-13

This means that probably `universum` doesn't build with GHC-8.4.1 which is both sad and strange at the same time.

**Comment by vrom911** [comment]
This is due to  `text-format` (see #157) . What should be done about it? I think that something is going on in `fmt` so we can make #158 .

**Comment by ChShersh** [comment]
@vrom911 I completely forgot about issues with `text-format`. Yeah, `text-format` should be replaced. I'd prefer to replace it with `fmt` instead of `formatting` by various reasons. Currently something is going on in `fmt` to resolve this issue:

* https://github.com/aelve/fmt/pull/21

**Comment by brandonhamilton** [comment]
The current version of `fmt` is [just re-exporting](https://github.com/aelve/fmt/blob/master/lib/Fmt.hs#L127) `Buildable` from `formatting`. Unless the other functions from `fmt` are also going to be exposed in `universum`, just switching to `fmt` does not gain any benefit over #158 at the moment (but would be beneficial after aelve/fmt#21 is completed). Either of these will be the path of least change to being buildable with `ghc-8.4` and getting back into `stackage-nightly`. 

I support your solution to remove `Buildable`, although that would lead to breaking change for users  of the `universum` library as you have mentioned.

**Comment by gromakovsky** [comment]
> Well, another option to resolve this issue: don't depend on any formatting library and don't reexport Buildable type class.

What about `pretty`? That function is cool, isn't it?

**Comment by ChShersh** [comment]
> although that would lead to breaking change for users of the universum library as you have mentioned.

Well, reexporing `Buildable` from other place is also a breaking change...

> What about pretty? That function is cool, isn't it?

In `fmt` library `pretty` is just [`fmt`](https://hackage.haskell.org/package/fmt-0.5.0.0/docs/Fmt.html#v:fmt) function. I think that it's formatting libraries who should care about having such nice functions to convert from `Buildable` into some text.

**Comment by neongreen** [comment]
I pinged Chris again

**Comment by neongreen** [comment]
https://hackage.haskell.org/package/fmt-0.6

**Comment by ChShersh** [comment]
I'm not sure which solution is better...

1. Replace `text-format` with `formatting`.
2. Replace `text-format` with `fmt`.
3. Remove `text-format` at all.

At the same time I want to make this decision ASAP so `universum` can appear in stable LTS with GHC-8.4.1 :running_man:

**Comment by gromakovsky** [comment]
> In fmt library pretty is just fmt function. I think that it's formatting libraries who should care about having such nice functions to convert from Buildable into some text.

Well, what I wanted to say is that in your *Cons* you probably forgot about `pretty`, removal of which is probably even worse than `Buildable`, because I can't import it from another place, so it's more breaking change (I see that I can import `fmt` instead, but it requires more changes). Of course it's not a fatal problem, just one more problem you didn't mention.

**Comment by volhovm** [comment]
I think that formatting library should not be a part of prelude anyway, so I vote for (3).
