### ISSUE TITLE
Force people to use NonEmpty

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#16]
Maybe we should export `NonEmpty` and force users to use it?
Also make our functions work with this data type.

**Comment by gromakovsky** [comment]
They appeared in base only in 4.9. Where are they prior to base 4.9? How will we deal with it?

**Comment by ChShersh** [comment]
@gromakovsky They (IDK why you used _they_, I was talking about only one data type) were in [semigroups](http://hackage.haskell.org/package/semigroups) package. Probably we can add some macros to configs... But I see your point. Personally I don't want to do it :(

**Comment by neongreen** [comment]
If you use base-4.9, `semigroups` will automatically reexport the type from base, so it's solved for us – we just need to depend on `semigroups`. No macros required.

This said, I'm somewhat against forcing everyone to use `NonEmpty`.

**Comment by neongreen** [comment]
`NonEmpty` is reexported in 0.2 so now this issue is only about forcing its usage.

**Comment by ChShersh** [comment]
This issue can be closed after merge. I'm okay with the fact that `NonEmpty` is exported. Also I agree it may be not a good idea to force people use `NonEmpty` (due to some reasons). So it's already ok.
