### ISSUE TITLE
Change the type of `readMaybe`

### ISSUE THREAD

**Issue by gromakovsky** [serokell/universum#165]
We have the following function: `readMaybe :: Read a => String -> Maybe a`.
I find it weird, because:
1. One of key points in the design of `Universum` is to avoid `String` as much as possible. However, this function's argument is `String`.
2. We also have `readEither :: (ToString a, Read b) => a -> Either Text b`, which takes anything convertible to `String` as an argument. This function is very similar to `readMaybe` and I think their arguments should have same types.

**Comment by ChShersh** [comment]
@gromakovsky I appreciate this change. But this is the breaking change since such code will no longer compile:

```haskell
readMaybe (show x) == Just x
```

Maybe we can sneak in this change into next major release :smirk: :smiling_imp:
