### ISSUE TITLE
Add Validation and probably replace Either with it

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#17]
Haskell has good old `Either` data type which is defined in next way:

`data Either a b = Left a | Right b`

This data type is very useful and awesome. But has one big problem: it is a matter of convention which constructor tag is chosen to represent errors. However, there exist more appropriate data type in `either` package: http://hackage.haskell.org/package/either-4.4.1.1/docs/Data-Either-Validation.html

``` haskell
data Validation e a
  = Failure e
  | Success a
```

I suppose we should introduce this data type as well and use it where possible instead of `Either`. It makes more sense. The only problem: I don't see why this data type neither `Monad` nor even `Applicative`.

**Comment by gromakovsky** [comment]
Btw, we have `Serokell.Util.Verify`, there is `VerificationRes`, but it's slightly different (e. g. its kind is `*`).

**Comment by ChShersh** [comment]
Ohh, this is an old issue... Time to clarify things.

`Validation` has different semantics. It doesn't have `Monad` instance. And we definitely not going to replace `Either` with something unknown. But exporting `Validation` in addition looks nice to me!

**Comment by volhovm** [comment]
Looks too complex for the prelude. I'd leave it in utils package.

**Comment by ChShersh** [comment]
It's not complex. But I don't think we need to add one more extra dependency. And we don't want to create our own data type. Looks like it's not used often. So I guess we don't need it for now.
