### ISSUE TITLE
Remove 'type-operators' dependency

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#174]
After gathering move feedback on `universum` usage we discovered that people don't actually use type operators. They can complicate code written with the help of `universum`, they can break some IDE tools. So it was proposed to remove `type-ops` dependency.

Maybe we can keep at least `$` type operator, but write it manually?

**Comment by gromakovsky** [comment]
I propose to do it in two steps: remove this dependency but keep all exports in 1.3.0 (copy-paste operators from `type-operators`) and then later decide whether type operators should be in Universum at all (as a separate issue probably).
