### ISSUE TITLE
Enable -Werror and few more warnings

### ISSUE THREAD

**Issue by gromakovsky** [serokell/universum#185]
I think we shouldn't permit warnings, but apparently we do.
Also I'd enable `-Wcompat -Wincomplete-uni-patterns -Wincomplete-record-updates -Wredundant-constraints`. You can read about them [here](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html). They seem to be harmless and helpful.

**Comment by Pastafarianist** [comment]
We can also use the same set of warnings as was recently introduced in Ariadne.

**Comment by gromakovsky** [comment]
https://github.com/serokell/ariadne/blob/624b379e508fcc926eca3dc8cf4c2af1d02a7147/hpack/definitions.yaml#L61
