### ISSUE TITLE
Lift `hClose`

### ISSUE THREAD

**Issue by kirelagin** [serokell/universum#186]
`Universum.Lifted.File` lift functions for opening, reading and writing files, but nothing to close them.

**Comment by gromakovsky** [comment]
I think there are two options: export `hClose` (lifted version) or remove export of `openFile` and export `withFile` instead (probably with `MonadMask` constraint, `MonadIO` is not enough) because one should use `withFile` whenever possible.
Or we can export all three :)

**Comment by gromakovsky** [comment]
Done in #200.
