### ISSUE TITLE
Exporting concatMap is confusing

### ISSUE THREAD

**Issue by JustusAdam** [serokell/universum#199]
The current version of `concatMap` exported is rather confusing.

Universum makes a point of condemning `Foldable`, yet it exports `concatMap :: Foldable f => (a -> [b]) -> t a -> [b]` rather than `concatMap :: Container c => (Element c -> [b]) -> c -> [b]`.

I read the concerns raised in #10 and while I agree, I think the export of `concatMap` should either have a `Container`ized type or be omitted entirely, or perhaps only have a deprecation warning.

**Comment by dcastro** [comment]
I think replacing the `Foldable` constraint with `Container` sounds sensible.
