### ISSUE TITLE
Include `lifted-async` imports

### ISSUE THREAD

**Issue by georgeee** [serokell/universum#20]
Universum currently exports e.g. `mapConcurrently`
We can use generalized versions from `lifted-async`

**Comment by ChShersh** [comment]
Yeah, generalized version sounds better. I don't see any objections rather than we will make `Universum` more fat...

**Comment by georgeee** [comment]
Not really fat. That module is just a bunch of typeclasses, no more
What about including `MonadBaseControl` as well?

**Comment by ChShersh** [comment]
People here discussing downsides of using `MonadBaseControl`:
https://www.reddit.com/r/haskell/comments/5o7id3/safeprelude_a_thought_experiment/dch7aft/

**Comment by gromakovsky** [comment]
I don't think `async` should be in `Universum` to be honest. It's not so fundamental.

**Comment by ChShersh** [comment]
I also think, that STM probably shouldn't be in `Universum` for same reasons. But at least names of `STM` don't clash with anything else. You probably wan't see `readTVar` function anywhere else. Though I'm okay with cutting off `async`.

**Comment by gromakovsky** [comment]
AFAIK, we don't have `readTVar`. We have only `atomically`, `retry`, etc. Not sure about `retry` actually.
Anyway, I am ok with `atomically`, but not with `retry`, it is not so uncommon name and it's not obvious that it's from STM.

**Comment by ChShersh** [comment]
Yeah, we definitely shouldn't put common names into custom prelude. I already noticed that sometimes we add `hiding` to `Universum`. For example, `bracket`, because it conflicts with `bracket` from `Mockable`. Though maybe this is not a `Universum` fault.

**Comment by gromakovsky** [comment]
I don't know why there is `bracket` in `Mockable`. Looks like reinventing `Control.Monad.Catch` 😕

**Comment by ChShersh** [comment]
`async` will be eliminated from dependencies (also conflicts with `Mockable`) and after that I'll close this issue finally.
And a lot of `IO` functions are already lifted. Using `liftted-*` packages is bad according to comments. Also, this is not basic thing and we are living happily a long time since then so nobody won't be unhappy with such plan.
