### ISSUE TITLE
Add benchmarks to `Universum`

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#21]
I suppose some functions should be benchmarked in order to investigate their performance and to see that we don't have some drawbacks.

First canditate: it may be good to add `hashNub` function near `ordNub`. Because it may be more efficient.

**Comment by ChShersh** [comment]
This benchmark shows that sometimes it make more sense to use `hashNub` function instead or implement `ordNub` in a different way to make more profit: https://github.com/ChShersh/effective-haskell/tree/master/nub

**Comment by ChShersh** [comment]
We must consider reading carefully all pragmas and fixing (adding) them appropriately according to this tutorial: http://mpickering.github.io/posts/2017-03-20-inlining-and-specialisation.html

**Comment by vrom911** [comment]
@ChShersh I would like to try myself in this one. But before that I would like to clarify what benchmarks need to be implemented additionally to `hashNub` and `ordNub`?

**Comment by Martoon-00** [comment]
How about:
1. Check whether `(...)` usage spoils performance when applied to many-arguments function, comparing with simple ways of function application
2. `concatMapM` vs `concatMap` when used monad is `Identity` (?)

**Comment by vrom911** [comment]
@Martoon-00 , thank for your suggestions!
I have a question about `(...)` operator. I don't see a good way to benchmark it, how do you think it could be done? Will we observe difference on some small examples, and how to come to bigger examples for that?

**Comment by Martoon-00** [comment]
Well, nice question )
I suppose, that if no difference is observed on very small examples, you have two ways of extension: apply resulting function to more arguments and apply `(...)` more times. If, say, 10 usages of `(...)` `x` application to 10 arguments doesn't increase time much (time stays within measurement error, my hope in that it will be enough), then we don't care in practice about possible further performance penult.

Does it sound reasonable?

**Comment by vrom911** [comment]
Fair enough. Thank you! :) Will try to implement that.
