### ISSUE TITLE
Use `lifted-base` for everything

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#22]
I.e. all `IO` functions we export should work in `MonadIO`.

**Comment by ChShersh** [comment]
I'm okay with converting all common `IO` functions like `putStrLn` from `IO` to `MonadIO`. It will make code cleaner, you won't need to write `liftIO` every time. Also this doesn't add overhead in general. We can add `INLINE`. And `IO` is slow anyway :)

So I don't see any drawbacks in moving from `IO` to `MonadIO`. Regardading `MonadBaseControl IO` and similar stuff... Dunno, seems like over-engineering.
