### ISSUE TITLE
Forbid `length` and some other functions for tuples/Maybe/etc

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#23]
If we add something like this

```haskell
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}

import qualified Data.Foldable as F
import Prelude hiding (length)

class Length a where
  length :: a -> Int

instance {-# OVERLAPPABLE #-} Foldable f => Length (f a) where
  length = F.length

class Length_For_This_Type_Is_Bad a

instance Length_For_This_Type_Is_Bad (a, b) => Length (a, b) where
  length = undefined

instance Length_For_This_Type_Is_Bad (Maybe a) => Length (Maybe a) where
  length = undefined
```

we wouldn't be able to use `length` on tuples and `Maybe`:

```haskell
> length (True, False)

<interactive>:95:1-6:
    No instance for (Length_For_This_Type_Is_Bad (Bool, Bool))
      arising from a use of 'length'
    In the expression: length (True, False)
    In an equation for 'it': it = length (True, False)
```

Bonus #⁠1: we could also define instances of `Length` for e.g. `Text` and `ByteString`.

Bonus #⁠2: we could use `TypeError` (starting from GHC 8) for [nicer error messages](https://www.reddit.com/r/haskell/comments/5jwbpc/typelevel_equivalent_of_error_raising_descriptive/).

**Comment by ChShersh** [comment]
:+1: For `TypeError` usage. But I'm not sure if we want to add this for `Text` and `ByteString`... It may slowdown runtime. And `backpack` seems to fix some problems with functions for different string representations.

**Comment by neongreen** [comment]
> But I'm not sure if we want to add this for Text and ByteString... It may slowdown runtime. 

Wait, how? With `{-# INLINE #-}` it shouldn't.

**Comment by ChShersh** [comment]
I'm not sure about only `{-# INLINE #-}` but maybe also with `{-# SPECIALIZE #-}` everything may be ok.

**Comment by neongreen** [comment]
Then we need to decide how to handle GHC 7.10

1. We can use `class Length_For_This_Type_Is_Bad a` for GHC 7.10 and `TypeError` for GHC 8
2. We can use `TypeError` and make Universum GHC 8–only
3. We can use CPP to make `length` Foldable-unsafe on GHC 7.10 and Foldable-safe on GHC 8

I like 1. the most and 3. the least.

**Comment by ChShersh** [comment]
I like 2 the most. Why care about earlier GHC? Things are moving forward. GHC 8.0.2 will appear next year. Why keep old compilers support if they are not so good? Just putting more effort into supporting old compilers and then putting some effort to remove this old compiler support. Less pragmas — better.

**Comment by neongreen** [comment]
> Why keep old compilers support if they are not so good?

Because we might – at some point – be asked to develop a project that uses GHC 7.10 (for various reasons). If you don't anticipate such a thing happening, then I'm fine with dropping support for 7.10.

**Comment by neongreen** [comment]
I went for (1).
