### ISSUE TITLE
Add string interpolation functionality

### ISSUE THREAD

**Issue by Martoon-00** [serokell/universum#246]
After some small discussion, we decided that using string interpolation via TH can be considered cool after all, so we need to export some support for this feature. 

We should consider using the existing libraries, hopefully, they will be enough to obtain the desired functionality or give us hints on a better interface, but if not - that should be fine to roll out our own solution.

To my knowledge, yet recently there was no interpolation library that would be just superb and could be picked as-is, so let's discuss what do we want.

**Comment by dcastro** [comment]
In light of the recent release of the awesome `nyan-interpolation`, should this issue be closed? :smile:

**Comment by Martoon-00** [comment]
Right :smile_cat: 

[Here](https://github.com/serokell/nyan-interpolation) is `nyan-interpolation` library.

---

Eventually I don't re-export it from `universum` because there are two variations of this interpolation library - [full-fledged one](https://hackage.haskell.org/package/nyan-interpolation) which depends on the heavyweight `haskell-src-exts` package, and [a lightweight one](https://hackage.haskell.org/package/nyan-interpolation-simple) without that dependency but which can interpolate only variables, not arbitrary expressions. 

In most cases, users will want the full version, but we cannot afford putting it to the prelude-like library.

[Morley](https://gitlab.com/morley-framework/morley) is an example of repository that preferred the lightweight interpolation.
