### ISSUE TITLE
Add vararg (.)

### ISSUE THREAD

**Issue by Martoon-00** [serokell/universum#25]
Maybe introduce some `(.:)`, where `f .: g` applies `f` to result of `g`, `g` accepts several arguments and returns monadic action?
For example `lift .:` seems to be handy

**Comment by neongreen** [comment]
I'm in favor of it.

**Comment by neongreen** [comment]
(Though I suspect type inference might not be so good, even for monadic actions. It'll likely get complicated by the fact that `(->)` is a monad as well. So, e.g. `lift .: forever` might not work.)

**Comment by neongreen** [comment]
Actually, maybe you should first check locally whether you even _can_ write a `(.:)` that would work for your purposes.

**Comment by neongreen** [comment]
(A possible candidate for an implementation: http://okmij.org/ftp/Haskell/polyvar-comp.lhs. There might be others.)

**Comment by Martoon-00** [comment]
Oh really, I didn't provide that `m a` and `r -> a` would overlap.
Will try implementation at your your link, thanks

**Comment by ChShersh** [comment]
I don't like vararg `(.)`. You can't say from code how many arguments it takes. It will become difficult to understand and maintain code. And you can have cryptic error messages. I better propose to add family of composition functions to specify number of arguments explicitly:
http://hackage.haskell.org/package/composition-1.0.2.1/docs/Data-Composition.html

I've already proposed to add such functions under origin issue. But @gromakovsky shared his concerns regarding performance degrade.
https://issues.serokell.io/issue/SRK-10#comment=96-242

**Comment by ChShersh** [comment]
Unfortunately, `(.:)` conflictis with `aeson`. So we should invent either our own syntax for multiple versions of `(.), (.:), (.:.), (.::), etc.` or do something else. But I really like those composition operators.

**Comment by ChShersh** [comment]
Implemented in this commit: https://github.com/serokell/universum/commit/8c263015cf0a5c75c6e649aa77563adc9b40631c
I like it. I think issue can be closed.
