### ISSUE TITLE
Convenient ways to work with `mtl` stack

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#26]
It's very inconvenient to use `flip runReaderT r` or (`runReaderT` r) to run monads from `mtl` stack because first argument of such functions is monad, not environment. I propose to add next functions:

```haskell
usingReaderT :: r -> ReaderT r m a -> m a
usingReader  :: r -> Reader r a -> a

usingStateT :: s -> StateT s m a -> m a
usingState  :: s -> State s a -> a
```

Maybe it's better to somehow force introduction of such functions directly inside `mtl`.

**Comment by gromakovsky** [comment]
> usingStateT :: s -> StateT s m a -> m a
It's questionable what this function should return. It can be analogue of `runStateT`, `execStateT`, `evalStateT`.

**Comment by ChShersh** [comment]
@gromakovsky Agree. But by our convention (also works good with `ReaderT`) it returns `m a`. And in that case we need to introduce new nice names.

**Comment by gromakovsky** [comment]
Well, this convention is not obvious, another possible convention can be that `using` is `flip run`. I can't say that one is better than another one though.
