### ISSUE TITLE
Export String

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#27]
It's needed sometimes (when working with code from other libraries that uses `String`) and it's annoying that it's not there. The lack of `String` doesn't even make anything safer because without `String` people either import `Data.String` or just use `[Char]` instead and carry on. `[Char]` is worse than `String`.

**Comment by ChShersh** [comment]
I don't like `String` :(

**Comment by neongreen** [comment]
![image](https://cloud.githubusercontent.com/assets/1523306/22035227/3b51d334-dd00-11e6-9b3e-dbc3f347c9b2.png)

**Comment by neongreen** [comment]
My point is that not including `String` into Universum doesn't stop anybody from using `String`. It just makes people's lives a bit harder _and_ makes getting rid of `String` a bit harder because instead of grepping `for `String` one now has to grep for both `String` and `[Char]` :)

**Comment by ChShersh** [comment]
Okay, you can add `String` type. I don't like it. From screenshot it looks to me like in some places `String` can be replaced with more sensible choice. And writing `[Char]` is not longer than writing `String`. But writing `[Char]` will make people feel bad about themselves while using this type and they will avoid its usages. Unfortunately, we can't solve famous _The String Problem_ with our `Universum` now. And we want library to be practical and useful now. So I can leave with that.
