### ISSUE TITLE
Make sure universum is part of LTS again

### ISSUE THREAD

**Issue by Martoon-00** [serokell/universum#288]
## Description

Universum fell off from the LTS.

This causes some of our badges contain invalid links and that causes CI to fail. I'm commenting those badges out in https://github.com/serokell/universum/pull/283.

Now we have to make sure that universum appears in the next LTS. Hopefully that very #283 will assist this.

## Acceptance criteria
* Universum is prepared to be included into the next LTS.
* Badges in our `README` are uncommented (check out the TODO in code)

**Comment by gromakovsky** [comment]
Started with Nightly: https://github.com/commercialhaskell/stackage/pull/7048

**Comment by gromakovsky** [comment]
Now it's included, so we need to update the badges.
