### ISSUE TITLE
Package doesn't compile with GHC 9.10

### ISSUE THREAD

**Issue by arybczak** [serokell/universum#296]
The fix is quite simple: https://github.com/arybczak/universum/commit/c96a371fca4bdca4a214fef44a0c98c31373b6d2

I didn't make a PR because I'll let you decide whether you want to use `-Wno-dodgy-imports` or use `CPP` to silence the warning in lower GHC versions :slightly_smiling_face:

**Comment by gromakovsky** [comment]
@arybczak thanks, I took the liberty to use `CPP`. Merged #297, created a new release: https://hackage.haskell.org/package/universum-1.8.2.2
