### ISSUE TITLE
Remove Semiring

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#3]
I never used it and in fact it's the first time I see it. Has anybody else used it? Can anybody say anything about it?

**Comment by Martoon-00** [comment]
Looks like typeclass for fans of mathematics only

**Comment by ChShersh** [comment]
Totally agree. _GHC 8_ and later lands with `Semigroup` and we may want to use those math abstractions. But I don't know any use case of `Semiring` except this mindblowing one: http://r6.ca/blog/20110808T035622Z.html

Thus I'm for removing this module to not confuse new people :) It is just not widely used. So why we need it?
