### ISSUE TITLE
Add 'catRights' and probably 'catLefts'

### ISSUE THREAD

**Issue by gromakovsky** [serokell/universum#31]
Subj.
`catRights = catMaybes . map hush`. Sometimes it's useful. Name is descriptive.

**Comment by ChShersh** [comment]
There're `lefts` and `rights` functions in `base` in `Data.Either` module:
http://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Either.html

I don't think it's worh to add them by default.

**Comment by gromakovsky** [comment]
TIL there are such functions in `base`.
