### ISSUE TITLE
Generalize functions with `String` param

### ISSUE THREAD

**Issue by ksaric** [serokell/universum#37]
Generalize functions with `String` param to support `Text` as well?
Would need to write a custom function, not reexport existing one, but seems very useful to me.

For example, I run into - https://github.com/sdiehl/protolude/blob/master/src/Protolude.hs#L521-L526 :
- `readEither` change to `readEither :: (IsString a, Read b) => a -> Either a b`
- `readMaybe` change to `IsString a` like above

**Comment by neongreen** [comment]
I'm for it, except that we'll have to use `ToString` instead of `IsString`. Also, in `readEither` I'd just return `Text` instead of `IsString a`.

**Comment by ChShersh** [comment]
@neongreen Why 

`readEither :: Read b => a -> Either Text b` 

is better than 

`readEither :: (ToString a, Read b) => a -> Either a b`

by your opinion?

**Comment by neongreen** [comment]
Because I don't think that polymorphism is necessary here (similarly to how we don't replace all instances of `Text` with `ToText a`)
