### ISSUE TITLE
Add `flip whenNothing`

### ISSUE THREAD

**Issue by Martoon-00** [serokell/universum#40]
`whenNothing` is cool, but it's often used like `getPatak >>= flip whenNothingM noPatak`
Let's add flipped version and call e.g. `fromMaybeM`?

**Comment by ChShersh** [comment]
Could you provide link to example? I don't see any usages of `flip whenNothingM` currently

**Comment by Martoon-00** [comment]
I'm working with wallet now, so examples are from there:
https://github.com/input-output-hk/cardano-sl/blob/master/src/Pos/Wallet/Web/Server/Methods.hs#L332
and 3 more like that nearby

**Comment by ChShersh** [comment]
Instead of `getProfile >>= maybe noProfile pure` you can use `whenNothingM getProfile noProfile`, no need in `flip`

**Comment by Martoon-00** [comment]
Sometimes that `getPatak` is quite large. But okay, it really doesn't worth creating new function, thanks for discussion
