### ISSUE TITLE
Add migration guide from Prelude

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#44]
I think `README.md` should contain migration guide how to easily migrate from `Prelude` to `Universum` mentioning some gotchas and most popular errors and differences that could cause compilation errors.

Things that can be mentioned:

* Replace `id` usages with `identity`.
* When using `head` use `fromMaybe (error "list is empty")` or rewrite code in more safe manner (but I really wish that #5 will be resolved earlier).
* Instead of using `tail`, `init`, `last`, `!!` use explicit functions like `tailMay` or `tailDef`.
* When using `foldr`, `fold`, `foldMap` or any `Foldable` function on `Maybe`, `Either` or tuple, replace it with `whenJust`, `maybe` or any other function.
* Mention, that if you have imports of `readIORef`, `newMVar`, `readTVarIO` or something similar you should remove those imports. Otherwise you will have some compilation errors because we lift those types to `MonadIO`.

Anything else?

**Comment by Martoon-00** [comment]
* Forget about `String`s:
** Replace `(++)` with `(<>)`
** Use `Formatting` library to construct messages where possible
** (except places where library force you to use `String`; better prefer using `toString` at such places)
* If use `putStr` or similar, note that it's type class function, you may need to specify type explicitelly
* Note that `toList` differs from one from `GHC.Exts`

**Comment by ChShersh** [comment]
@Martoon-00  Not `Formatting` but [`fmt`](https://github.com/aelve/fmt) instead ;)

> If use putStr or similar

Yes, told about `putText` and enabling `-XOverloadedStrings` is good.

> Note that toList differs from one from GHC.Exts

Mmm... How it matters? Almost nobody uses `toList` from `GHC.Exts`. Everyone is using `Foldable`'s one.

**Comment by Martoon-00** [comment]
> @Martoon-00 Not Formatting but fmt instead ;)

➕ 

> Mmm... How it matters? Almost nobody uses toList from GHC.Exts. Everyone is using Foldable's one.

ahah, I'm in minority. Didn't notice that your `toList` is same as `Foldable`'s one

**Comment by ChShersh** [comment]
Describe how to move from `Foldable f => f a` to `Container` type class.
