### ISSUE TITLE
Add 'maybeToMonoid'?

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#52]
I propose to add next function:

```haskell
maybeToMonoid :: Monoid m => Maybe m -> m
maybeToMonoid = maybe mempty id
```

When there was `Foldable` for `Maybe`, `maybeToMonoid` is just `fold`. But I think that this function is useful. And it's behavior and type is clear from name, also what it does and how also clear from type.

**Comment by gromakovsky** [comment]
Btw, `maybe a id` is `fromMaybe a`.

**Comment by ChShersh** [comment]
@gromakovsky Even better :)

**Comment by ChShersh** [comment]
One more convenient function is `maybeWithMonoid :: Monoid m => Maybe a -> (a -> m) -> m`. After it `maybeToMonoid x` becomes just `maybeWithMonoid x id`.
