### ISSUE TITLE
Specify policy about version bounds inside .cabal file

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#54]
[Here](https://github.com/serokell/universum/blob/f7c7edcee95a630f090d142f8950571c7326516a/universum.cabal#L62) we has some mix of version bounds — somewhere no bound, somewhere exact version and mostly both bounds are specified. This looks like mess. I prefer to organize dependencies in uniform way. Probably we should also upgrade out [style-guide](https://github.com/serokell/serokell-util/blob/master/serokell-style.md).

**Comment by ChShersh** [comment]
I propose next policy: 

1. Remove all dependencies from `.cabal` file.
2. Upload to hackage with `--pvp-bounds=both`.

**Comment by ChShersh** [comment]
@vrom911 As I understood correctly, you can do this issue :slightly_smiling_face:

**Comment by vrom911** [comment]
Yes, certainly! I'm in :blush:
