### ISSUE TITLE
Make 'Element' an associated type family

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#58]
It was suggested under comments to [this answer on SO](https://stackoverflow.com/questions/45424976/foldable-intset/45425178#comment77841903_45425178).

**Comment by ChShersh** [comment]
@neongreen @int-index Could you please comment on this?

**Comment by int-index** [comment]
I do not have a strong opinion either way. An associated type family should work for this use case.

**Comment by ChShersh** [comment]
One more reason to have associated type family:

We can implement `WrappedList` wrapper in more general way:

```haskell
newtype WrappedList t = WrappedList t

instance ToList t => ToList (WrappedList t) where
    type Element (WrappedList t) = Element t
```

Now it's not possible because of conflicting instance:

```haskell
type instance Element (f a) = a
```

**Comment by int-index** [comment]
> type instance Element (f a) = a

Do we have this instance at top level at the moment? Yes, it should be made into a default definition of the associated type family.

**Comment by ChShersh** [comment]
It's not possible to implement this in current `universum` design because we have `{-# OVERLAPPABLE #-}` instance and open type families can't be overlappable (as @int-index explained me). Related SO question:

https://stackoverflow.com/questions/47816268/how-to-implement-default-associated-type-family-for-overlappable-instance-monom
