### ISSUE TITLE
Numeric.Natural

### ISSUE THREAD

**Issue by int-index** [serokell/universum#60]
Re-export it from `base`.

**Comment by ChShersh** [comment]
Can also propose to export [`GHC.TypeNats`](http://hackage.haskell.org/package/base-4.10.0.0/docs/GHC-TypeNats.html) instead of [`GHC.TypeLits`](http://hackage.haskell.org/package/base-4.10.0.0/docs/GHC-TypeLits.html).

**Comment by ChShersh** [comment]
OMG, I just noticed that PR reexports only `GHC.TypeNats` not `Numeric.Natural`
