### ISSUE TITLE
Add 'sortNub' and 'unstableNub' to 'universum'

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#68]
Results in PR #66 show next things:

1. `hashNub` is faster than `ordNub` when there're not so many different keys.
2. When you're using `Text` data type than `hashNub` is faster.
3. `sortNub = Set.toList . Set.fromList` has better performance than `ordNub` but should be used when you also need sorting.
4. `unstableNub = HashSet.toList . HashSet.fromList` has better performance than `hashNub`.

So, all new functions should be added to `universum` and documented properly with use cases and examples.

@vrom911 Tell me if you have interest in implementing this issue as well :)

**Comment by vrom911** [comment]
I'm interested! :)
