### ISSUE TITLE
Add stack trace to `panic`

### ISSUE THREAD

**Issue by neongreen** [serokell/universum#7]
Once we use GHC 8 everywhere, they'll be useful. (I don't know anything about stack traces though – is it even possible to add them to `panic`?)

**Comment by ChShersh** [comment]
I suppose it is possible. We should copy signature of `error` from `base 4.9.0.0` to `panic`. And probably to all our `error` and family functions.
http://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.Err.html#error
