### ISSUE TITLE
Hide doc examples under spoiler

### ISSUE THREAD

**Issue by Martoon-00** [serokell/universum#71]
Examples bump up documentation much, and sometimes I find scrolling through haddock unpleasant for that reason.
For instance, see https://hackage.haskell.org/package/universum-0.7.0/docs/Monad-Either.html .  One can easily understand what function does just from its name, but searching for specific function is hampered.

Just look how it's done for `void`: http://hackage.haskell.org/package/base-4.10.0.0/docs/Control-Monad.html#v:void
I suggest it's cool feature and it's worth following this style.

**Comment by ChShersh** [comment]
@Martoon-00 Feature with hidden examples is really interesting. But not everyone likes it. Personally I also don't like to hide examples. See some discussions in my PR to `path` library:

https://github.com/commercialhaskell/path/pull/106#discussion_r124562362

**Comment by Martoon-00** [comment]
Oh lol, so it's known thing and has been discussed out. Okay, let's go as we do now
