### ISSUE TITLE
Import '(<>)' from Semigroup, not Monoid

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#79]
For example, it's not very convenient to use `Semigroup.<>` when you need to append `NonEmpty a`.

**Comment by neongreen** [comment]
We already had `<>` from Semigroup in Universum and then we changed it because it was too much hassle ;)

**Comment by ChShersh** [comment]
@neongreen Can you give an example of that? Probably I didn't face this issue...

**Comment by neongreen** [comment]
IIRC there were some types without `Monoid` instances and so we had to import the Monoid `(<>)` fairly often. I don't remember which types those were.

**Comment by int-index** [comment]
We should've added Semigroup instances upstream, since it's in base

**Comment by neongreen** [comment]
Meanwhile I have found the relevant commit and it looks like there were only six modules where we had to hide `(<>)` from Universum. We are also using `NonEmpty` more often now so I guess I'm fine with exporting `(<>)` from `Semigroup` instead of `Monoid` provided that we also export `mappend`.

**Comment by ChShersh** [comment]
We can just use `mappend` if we need `Monoid`.
When `Semigroup => Monoid` lands in GHC 8.4.1 it will become much easier to migrate. Especially if we try by ourselves to use `Semigroup` instead of `Monoid` as much as possible.

**Comment by gromakovsky** [comment]
IIRC, most annoying example was some famous type from `optparse-applicative`.

**Comment by ChShersh** [comment]
@gromakovsky This data type has `instance Semigroup` in last version of `optparse-applicative`.
