### ISSUE TITLE
`putText` and `putTextLn`

### ISSUE THREAD

**Issue by vrom911** [serokell/universum#81]
For the moment there is only `putText` function in `universum` which behaves like `putStrLn`. 
I think it would be convenient to have `putText` which would be specialized version of `putStr` and `putTextLn` — version of `putStrLn`.

**Comment by vrom911** [comment]
@ChShersh, it's really sad..( 
Probably we could name the new one as `putTextInline` then, so there won't be any conflicts? Or any other more suitable alternative?

**Comment by gromakovsky** [comment]
`universum-1.0.0` 😉

**Comment by ChShersh** [comment]
@gromakovsky I want #5 be done before releasing `universum-1.0.0`.. And probably something else before we will announce `universum`.

**Comment by ChShersh** [comment]
So the solution is:

1. Rename `putText` to `putTextLn`
2. Add `putText` whish is equsl to `putStr`.
