### ISSUE TITLE
Change the order of types in `show`

### ISSUE THREAD

**Issue by vrom911** [serokell/universum#83]
For the moment
```haskell
show :: (Show a, IsString b) => a -> b
```
It would be better to have on the first position the returned type, rather that received. So you don't need to write something like: `show @_ @Text x` but just `show @Text x`.

**Comment by ChShersh** [comment]
@vrom911 I agree! It would be nice to fix this. `print` function has the same problem:

https://github.com/serokell/universum/blob/a2ebb28430105351fbf5a71262e9b4e7521422ae/src/Universum.hs#L204

This should be solved using `forall` keyword to specify explicitly order of arguments, like this:


```haskell
show :: forall b a . (Show a, IsString b) => a -> b
```

I wouldn't rely on type variables order of appearance... In such cases it's better to explicitly specify desired order.
