### ISSUE TITLE
Add showPretty

### ISSUE THREAD

**Issue by gromakovsky** [serokell/universum#9]
Let's add `showPretty :: Buildable a => a -> Text`. Or maybe somebody has a better name. Anyway, this function is needed I think. And probably we also need a version which returns lazy `Text`.

After that we can remove `show'` from `serokell-core`.

**Comment by ChShersh** [comment]
I can see that this issue has something similar with reexporting `Buildable` from `Universum`.
But consider only `showPretty` function: I like it. We can add one :)
I found function `pretty` with exact same type on _Stackage_. So we can call it `pretty`. 
Other names: `showBuild` `buildShow` `bshow` `tshow` `prettyShow` `buildT` `buildPretty`.

**Comment by neongreen** [comment]
What exactly would `showPretty` do? Specifically, how would the output be “pretty”?

**Comment by gromakovsky** [comment]
It will do the same thing as `Serokell.Util.Text.show'`: `LT.toStrict . B.toLazyText . build`. Probably we also need a version which returns `LText`.

We can generalize it to `(StringConv Text b, Buildable a) => a -> b`, but I am not sure if it is good idea.

Output would be pretty, because the idea behind `Buildable` is to provide more pretty representation than `Show`.

**Comment by ChShersh** [comment]
Added two functions: `pretty` and `pretty'` like `show` and `show'` from `serokell` but with `'` swapped.
https://github.com/serokell/serokell-core/blob/master/src/Serokell/Util/Text.hs#L64

Also, some new questions:

* Should we export `Buildable (build)` or at least only `Buildable`?
* Maybe make version of `pretty` somehow not use `pretty'`?

**Comment by gromakovsky** [comment]
About 1: I propose to export only `Buildable`, because `build` conflicts with `formatting`.
