### ISSUE TITLE
Change arguments order for foldl'

### ISSUE THREAD

**Issue by ChShersh** [serokell/universum#91]
Currently `foldl'` function has next type:

```haskell
foldl' :: forall a b . (b -> a -> b) -> b -> [a] -> b
```

This type signature is not very convenient to use. Consider function where you want to insert elements of list one by one into `HashSet` (this is trivial example, but in practice something structurally similar appears very often):

```haskell
foo :: Hashable key => [key] -> HashSet key
foo = foldl' (flip HashSet.insert) mempty
```

You either add `flip` or write your own function inside `where`. Or use `foldr`, but `foldr` performance is abysmal and such implementation will have space leak (TODO: benchmark and profile to prove it). It's a common pattern in Haskell where data structure is the last argument of function. Because it's convenient to use so. But when you want to use this pattern with `foldl'` you can't rely on eta-reduce anymore :( You can't just write

```haskell
foo :: Hashable key => [key] -> HashSet key
foo = foldl' HashSet.insert mempty
```

So I propose to have our `foldl'` with arguments changed:

```haskell
foldl' :: forall a b . (a -> b -> b) -> b -> [a] -> b
```

This should be implemented using `foldl'` from `base`. And some benchmarks should be added as well. I checked `GHC.List` module and didn't notice presence of `foldl'` inside `RULES` pragmas. So this change can be performed without performance penalties.

**DRAWBACKS**
1. Unexpected arguments order for users of `foldl'` from `base` (shouldn't be very important because not many people uses `foldl'`)
2. Potential performance penalties if we implement `foldl'` in a wrong way.

**ADVANTAGES**
1. More convenient library API.

**Comment by ChShersh** [comment]
Done in PR #106.

**Comment by flyingleafe** [comment]
Wow, this is actually an API-breaking change which was done via incrementing patch version instead of major version (!). Why would you ever do that?
Also, it's super weird when `foldl` and `foldl'` have different type signatures, it's completely counter-intuitive.

(Got frustrated recently after a failed attempt to build several packages from `cardano-sl-*` family with new Universum)

**Comment by ChShersh** [comment]
@flyingleafe version change was already discussed.

>  it's super weird when foldl and foldl'

You shouldn't use `foldl` anyways. And `universum` shouldn't export `foldl` if it does this now. So it doesn't matter at the end.

> (Got frustrated recently after a failed attempt to build several packages from cardano-sl-* family with new Universum)

You just need to wait for this PR to be merged:

* https://github.com/input-output-hk/cardano-sl/pull/2327
